# -*- coding: utf-8 -*-
"""MNIST using HOG and SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WlSwCgQo6zfP121f1Kerjqyd5YsezOLs

# * Using HOG and SVM

 <tab><tab>- Sử dụng HOG(histogram oriented of gradient) để extract feature <br>
 <tab><tab>- Đưa vào model SVM để phân loại <br>
 <tab><tab>- Dùng opencv đế segmentation digit và dùng model chúng ta vừa build để predict

## * MNIST Dataset Overview

The dataset contains 60,000 examples for training and 10,000 examples for testing. The digits have been size-normalized and centered in a fixed-size image (28x28 pixels) with values from 0 to 1. For simplicity, each image has been flattened and converted to a 1-D numpy array of 784 features (28*28).

![MNIST Dataset](http://neuralnetworksanddeeplearning.com/images/mnist_100_digits.png)

# **1.** **Load Dataset và Load các thư viện cần dùng**
"""

import cv2
import numpy as np
from skimage.feature import hog
from sklearn.svm import LinearSVC
from keras.datasets import mnist
from sklearn.metrics import accuracy_score
#load data
(X_train,y_train),(X_test,y_test) = mnist.load_data()

"""# **2. Tính HOG**"""

#cho x_train
X_train_feature = []
for i in range(len(X_train)):
    feature = hog(X_train[i],orientations=9,pixels_per_cell=(14,14),cells_per_block=(1,1),block_norm="L2")
    X_train_feature.append(feature)
X_train_feature = np.array(X_train_feature,dtype = np.float32)

#cho x_test
X_test_feature = []
for i in range(len(X_test)):
    feature = hog(X_test[i],orientations=9,pixels_per_cell=(14,14),cells_per_block=(1,1),block_norm="L2")
    X_test_feature.append(feature)
X_test_feature = np.array(X_test_feature,dtype=np.float32)

"""# **2. Build model vào predict**"""

modelHOG = LinearSVC(C=10)
modelHOG.fit(X_train_feature,y_train)
y_pre = modelHOG.predict(X_test_feature)
print(accuracy_score(y_test,y_pre))

from google.colab import drive
drive.mount('/content/drive')

"""# **3. Predict trên ảnh có nhiều ditgit**"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
#The line above is necesary to show Matplotlib's plots inside a Jupyter Notebook

import cv2
from matplotlib import pyplot as plt
image = cv2.imread("/content/drive/My Drive/Colab Notebooks/Digit regconition/digit.jpg")
plt.imshow(image)
plt.show()

image = cv2.imread("/content/drive/My Drive/Colab Notebooks/Digit regconition/digit.jpg")
im_gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
im_blur = cv2.GaussianBlur(im_gray,(5,5),0)
im, thre = cv2.threshold(im_blur,90,255,cv2.THRESH_BINARY_INV)
contours, hierarchy = cv2.findContours(thre, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
rects = [cv2.boundingRect(cnt) for cnt in contours]

for i in contours:
    (x,y,w,h) = cv2.boundingRect(i)
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),3)
    roi = thre[y:y+h,x:x+w]
    roi = np.pad(roi,(20,20),'constant',constant_values=(0,0))
    roi = cv2.resize(roi, (28, 28), interpolation=cv2.INTER_AREA)
    roi = cv2.dilate(roi, (3, 3))
    
    # Calculate the HOG features
    roi_hog_fd = hog(roi, orientations=9, pixels_per_cell=(14, 14), cells_per_block=(1, 1),block_norm="L2")
    nbr = modelHOG.predict(np.array([roi_hog_fd], np.float32))
    cv2.putText(image, str(int(nbr[0])), (x, y),cv2.FONT_HERSHEY_DUPLEX, 2, (0, 255, 255), 3)
    #cv2.imshow("image",image)
    plt.imshow(image)
    plt.show()
cv2.imwrite("image_pand.jpg",image)
cv2.waitKey()
cv2.destroyAllWindows()